import Head from 'next/head';

export default function Head() {
	return (
		<>
			<title>PAUL ALEX - Software Developer</title>
			<meta content="width=device-width, initial-scale=1" name="viewport" />
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="favicon.ico" sizes="any" />
		</>
	);
}
